name: Deploy to Server

on:
  push:
    branches:
      - prod-ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Copy .env.production to .env
        run: cp .env.production .env

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install and build npm dependencies
        run: |
          npm install
          npm run build

      - name: Connect to the server via SSH
        uses: appleboy/ssh-action@v0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /path/to/site

            if [ -d "project_directory" ]; then
              cd project_directory
              php artisan down

              composer install --optimize-autoloader --no-dev
              
              git fetch origin main
              git reset --hard origin/main

              php artisan migrate --force
              php artisan queue:restart
              php artisan optimize

              php artisan up
            else
              git clone ${{ github.repository }} project_directory
              
              composer install --optimize-autoloader --no-dev
              
              php artisan key:generate
              php artisan migrate:fresh --seed
              php artisan storage:link

              php artisan config:cache
              php artisan view:cache
              php artisan route:cache
            fi

    
  
